export enum TicketErrorCode {
  NOT_FOUND = 'TICKET_NOT_FOUND',
  ALREADY_CLOSED = 'TICKET_ALREADY_CLOSED',
  OPEN_LIMIT_EXCEEDED = 'TICKET_OPEN_LIMIT_EXCEEDED',
  NOT_ASSIGNED_TO_YOU = 'TICKET_NOT_ASSIGNED_TO_YOU',
}
